### PR TITLE
Removing mention of non-existing parameter

### PR DESCRIPTION
**Pull request by Dzhuneyt**
Removing mention of non-existing parameter: always_issue_new_refresh_token

| Q             | A
| ------------- | ---
| Is bugfix?    | yes/no
| New feature?  | yes/no
| Breaks BC?    | yes/no
| Tests pass?   | yes/no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Comment by Dzhuneyt** [comment]
@Faryshta @neverabe any chance you can do a code review of the above so we can merge it?

**Comment by Faryshta** [comment]
I am checking the code on the bshaffer repository and the property exists

https://github.com/bshaffer/oauth2-server-php/blob/master/src/OAuth2/GrantType/RefreshToken.php#L35

Its a property passed to the constructor so its not alike to the way we do it in yii2.

Are you getting any form or error @Dzhuneyt ?

**Comment by Dzhuneyt** [comment]
No errors, but this is a Yii2 library, that wraps the original "pure PHP" implementation. I think it should follow Yii2's standard practices, which state that objects defined under "modules" or "components" of the configuration array, should follow the structure of the "[configuration object](https://www.yiiframework.com/doc/guide/2.0/en/concept-configurations)".

To better quote:

> Configurations are widely used in Yii when creating new objects or initializing existing objects. Configurations usually include the class name of the object being created and a list of initial values that should be assigned to the object's properties.

Additionally, the Yii2 plugin for PHPStorm (a widely used IDE) highlights this as a possible error.

**Comment by Faryshta** [comment]
I dont know how to fix the PHPStorm warning but Yii2 Dependency Injection allows to define objects the way its documented, in this case a constructor parameter is being passed on the configuration.

https://www.yiiframework.com/doc/guide/2.0/en/concept-di-container

> Behind the scene, the DI container does much more work than just creating a new object. The container will first inspect the class constructor to find out dependent class or interface names and then automatically resolve those dependencies recursively.

**Pull request closed without merging**
